version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-risk-engine-api
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=development
      - PORT=6000
      - MONGODB_URI=mongodb://mongodb:27017/ai-risk-engine
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - mongodb
    command: npm run dev
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ai-risk-engine-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: 